### ISSUE TITLE
KeyError: 'report_type' when installing Aeroo Report module

### ISSUE THREAD

**Issue by mgielissen** [jamotion/aeroo#18]
Installing LibreOffice headless with Ubuntu 14.04 works.  But when I install the module report_aeroo, I get this error:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 526, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 563, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 792, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 152, in load_module_graph
    models = registry.load(cr, package)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 162, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/odoo-server/openerp/models.py", line 651, in _build_model
    model.__init__(pool, cr)
  File "/opt/odoo/custom/addons/report_aeroo/report_xml.py", line 729, in __init__
    self._columns['report_type'].selection.append(('aeroo', 'Aeroo'))
KeyError: 'report_type'

**Comment by mgielissen** [comment]
Problem solved, the Aeroo Reports module from apps.odoo.com works.

**Comment by Sathors** [comment]
I can confirm that the official release of aeroo reports present in [apps.odoo.com](https://www.odoo.com/apps/modules/8.0/report_aeroo/) is now working so far as I can tell.
